# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.5
  # - release
  # - nightly
notifications:
  email: false
# uncomment the following lines to override the default test script
script:
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - julia -e 'Pkg.clone(pwd()); Pkg.add("JuLIP"); Pkg.checkout("JuLIP"); Pkg.clone("https://github.com/ettersi/FermiContour.jl"); Pkg.build("TightBinding.jl"); Pkg.test("TightBinding.jl"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("TightBinding.jl")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("TightBinding.jl")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
